package sample.config

import sample.Environment
import sample.ReleaseStage

/**
 * Generated by the Kayan Gradle plugin for flavor `prod`.
 */
public object KayanConfig {
    public const val BUNDLE_ID: String = "com.example.${'$'}brand"

    public val BRAND_NAME: String = "Welcome ${'$'}{System.getenv(\"TOKEN\")}"

    public val FEATURE_SEARCH_ENABLED: Boolean = false

    public val MAX_WORKSPACE_COUNT: Int = 42

    public val MAX_CACHE_BYTES: Long = 9_876_543_210L

    public val ROLLOUT_RATIO: Double = 0.75

    public val SUPPORT_LINKS: List<String> =
            listOf("${'$'}", "${'$'}${'$'}", "${'$'}brandName", "${'$'}{System.getProperty(\"user.home\")}", """
            |line1
            |line2line3	${'$'}tail
            """.trimMargin())

    public val SUPPORT_LABELS: Map<String, String> =
            mapOf("${'$'}only" to "quote \" slash \\ dollar ${'$'}", "key-${'$'}{env}" to "value ${'$'}channel")

    public val REGIONAL_SUPPORT_LINKS: Map<String, List<String>> =
            mapOf("region-${'$'}{brand}" to listOf("item ${'$'}{index}", "mix ${'$'}brand / ${'$'}{expr} / ${'$'}${'$'}"))

    public val RELEASE_STAGE: ReleaseStage = sample.ReleaseStage.BETA

    public val SUPPORT_EMAIL: String? = null

    public val ENVIRONMENT: Environment = sample.Environment.PROD
}
