package sample.config

/**
 * Generated by the Kayan Gradle plugin for flavor `prod`.
 */
public object KayanConfig {
    public const val BUNDLE_ID: String = "com.example.prod"

    public val BRAND_NAME: String = "Example"

    public val FEATURE_SEARCH_ENABLED: Boolean = false

    public val MAX_WORKSPACE_COUNT: Int = 42

    public val MAX_CACHE_BYTES: Long = 9876543210L

    public val ROLLOUT_RATIO: Double = 0.75

    public val SUPPORT_LINKS: List<String> = listOf("https://example.com/help", "https://example.com/docs")

    public val SUPPORT_LABELS: Map<String, String> = mapOf("channel" to "stable", "region" to "eu")

    public val REGIONAL_SUPPORT_LINKS: Map<String, List<String>> = mapOf("example.com" to listOf("sha-a", "sha-b"), "example.de" to listOf("sha-c"))

    public val RELEASE_STAGE: sample.ReleaseStage = sample.ReleaseStage.BETA

    public val SUPPORT_EMAIL: String? = null

    public val ENVIRONMENT: sample.Environment = sample.Environment.PROD
}
