package io.kayan.gradle

import io.kayan.ConfigDefinition
import io.kayan.ConfigSchema
import io.kayan.ConfigValue
import io.kayan.ConfigValueKind
import io.kayan.ResolvedFlavorConfig

internal data class RenderedCustomProperty(
    val typeName: String,
    val expression: String?,
)

internal object KayanConfigGenerator {
    fun generate(
        packageName: String,
        className: String,
        schema: ConfigSchema,
        resolvedFlavorConfig: ResolvedFlavorConfig,
        renderedCustomProperties: Map<ConfigDefinition, RenderedCustomProperty> = emptyMap(),
    ): String {
        val properties = schema.entries.joinToString(separator = "\n\n") { definition ->
            buildProperty(
                definition = definition,
                value = resolvedFlavorConfig.values[definition],
                renderedCustomProperty = renderedCustomProperties[definition],
            )
        }

        return """
            |package $packageName
            |
            |/**
            | * Generated by the Kayan Gradle plugin for flavor `${resolvedFlavorConfig.flavorName}`.
            | */
            |public object $className {
            |$properties
            |}
        """.trimMargin()
    }

    private fun buildProperty(
        definition: ConfigDefinition,
        value: ConfigValue?,
        renderedCustomProperty: RenderedCustomProperty?,
    ): String =
        if (renderedCustomProperty != null) {
            val typeName = renderedCustomProperty.typeName
            val expression = renderedCustomProperty.expression
            if (expression == null) {
                "    public val ${definition.propertyName}: $typeName? = null"
            } else {
                "    public val ${definition.propertyName}: $typeName = $expression"
            }
        } else {
            when (value) {
                null,
                is ConfigValue.NullValue -> {
                    "    public val ${definition.propertyName}: ${
                        nullableTypeName(definition)
                    } = null"
                }
                else -> buildBuiltInProperty(definition, value)
            }
        }

    private fun buildBuiltInProperty(
        definition: ConfigDefinition,
        value: ConfigValue,
    ): String = when (value) {
        is ConfigValue.StringValue -> buildScalarProperty(
            definition = definition,
            typeName = "String",
            literal = escapeString(value.value),
        )

        is ConfigValue.BooleanValue -> buildScalarProperty(
            definition = definition,
            typeName = "Boolean",
            literal = value.value.toString(),
        )

        is ConfigValue.IntValue -> buildScalarProperty(
            definition = definition,
            typeName = "Int",
            literal = value.value.toString(),
        )

        is ConfigValue.LongValue -> buildScalarProperty(
            definition = definition,
            typeName = "Long",
            literal = "${value.value}L",
        )

        is ConfigValue.DoubleValue -> buildScalarProperty(
            definition = definition,
            typeName = "Double",
            literal = renderDouble(value.value),
        )

        is ConfigValue.StringMapValue -> {
            "    public val ${definition.propertyName}: Map<String, String> = ${renderStringMap(value.value)}"
        }

        is ConfigValue.StringListValue -> {
            "    public val ${definition.propertyName}: List<String> = ${renderStringList(value.value)}"
        }

        is ConfigValue.StringListMapValue -> {
            "    public val ${definition.propertyName}: Map<String, List<String>> = ${renderStringListMap(value.value)}"
        }

        is ConfigValue.EnumValue -> {
            "    public val ${definition.propertyName}: ${rawTypeName(definition)} = ${
                renderEnumValue(
                    definition,
                    value
                )
            }"
        }

        is ConfigValue.NullValue -> error("Null values should be handled before built-in property rendering.")
    }

    private fun buildScalarProperty(
        definition: ConfigDefinition,
        typeName: String,
        literal: String,
    ): String {
        val qualifier = if (definition.required) "const val" else "val"
        return "    public $qualifier ${definition.propertyName}: $typeName = $literal"
    }

    private fun nullableTypeName(definition: ConfigDefinition): String = "${rawTypeName(definition)}?"

    private fun rawTypeName(definition: ConfigDefinition): String = when (definition.kind) {
        ConfigValueKind.STRING -> "String"
        ConfigValueKind.BOOLEAN -> "Boolean"
        ConfigValueKind.INT -> "Int"
        ConfigValueKind.LONG -> "Long"
        ConfigValueKind.DOUBLE -> "Double"
        ConfigValueKind.STRING_MAP -> "Map<String, String>"
        ConfigValueKind.STRING_LIST -> "List<String>"
        ConfigValueKind.STRING_LIST_MAP -> "Map<String, List<String>>"
        ConfigValueKind.ENUM -> requireNotNull(definition.enumTypeName)
    }

    private fun renderStringMap(values: Map<String, String>): String =
        values.entries
            .sortedBy { it.key }
            .joinToString(prefix = "mapOf(", postfix = ")", separator = ", ") { (key, entryValue) ->
                "${escapeString(key)} to ${escapeString(entryValue)}"
            }

    private fun renderStringList(values: List<String>): String =
        values.joinToString(prefix = "listOf(", postfix = ")", separator = ", ") { escapeString(it) }

    private fun renderStringListMap(values: Map<String, List<String>>): String =
        values.entries
            .sortedBy { it.key }
            .joinToString(prefix = "mapOf(", postfix = ")", separator = ", ") { (key, entries) ->
                "${escapeString(key)} to ${renderStringList(entries)}"
            }

    private fun renderEnumValue(
        definition: ConfigDefinition,
        value: ConfigValue.EnumValue,
    ): String = "${requireNotNull(definition.enumTypeName)}.${value.value}"

    private fun renderDouble(value: Double): String {
        val rendered = value.toString()
        return if ('.' in rendered || 'e' in rendered.lowercase()) rendered else "$rendered.0"
    }

    private fun escapeString(value: String): String = buildString {
        append('"')
        value.forEach { character ->
            when (character) {
                '\\' -> append("\\\\")
                '"' -> append("\\\"")
                '\n' -> append("\\n")
                '\r' -> append("\\r")
                '\t' -> append("\\t")
                else -> append(character)
            }
        }
        append('"')
    }
}
