package io.kayan.gradle

import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeName
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.asClassName
import com.squareup.kotlinpoet.asTypeName
import io.kayan.ConfigDefinition
import io.kayan.ConfigSchema
import io.kayan.ConfigValue
import io.kayan.ConfigValueKind
import io.kayan.ResolvedFlavorConfig

internal data class RenderedCustomProperty(
    val typeName: TypeName,
    val expression: String?,
)

internal object KayanConfigGenerator {
    fun generate(
        packageName: String,
        className: String,
        schema: ConfigSchema,
        resolvedFlavorConfig: ResolvedFlavorConfig,
        renderedCustomProperties: Map<ConfigDefinition, RenderedCustomProperty> = emptyMap(),
    ): String {
        val objectSpec = TypeSpec.objectBuilder(className)
            .addModifiers(KModifier.PUBLIC)
            .addKdoc("Generated by the Kayan Gradle plugin for flavor `%L`.\n", resolvedFlavorConfig.flavorName)

        schema.entries
            .map { definition ->
                buildProperty(
                    definition = definition,
                    value = resolvedFlavorConfig.values[definition],
                    renderedCustomProperty = renderedCustomProperties[definition],
                )
            }
            .forEach(objectSpec::addProperty)

        return FileSpec.builder(packageName, className)
            .addKotlinDefaultImports(true, true)
            .indent("    ")
            .addType(objectSpec.build())
            .build()
            .toString()
    }

    private fun buildProperty(
        definition: ConfigDefinition,
        value: ConfigValue?,
        renderedCustomProperty: RenderedCustomProperty?,
    ): PropertySpec =
        if (renderedCustomProperty != null) {
            buildCustomProperty(definition, renderedCustomProperty)
        } else {
            when (value) {
                null,
                is ConfigValue.NullValue -> buildNullableProperty(
                    definition = definition,
                    typeName = typeNameFor(definition).copy(nullable = true),
                )

                else -> buildBuiltInProperty(definition, value)
            }
        }

    private fun buildCustomProperty(
        definition: ConfigDefinition,
        renderedCustomProperty: RenderedCustomProperty,
    ): PropertySpec {
        val typeName = renderedCustomProperty.typeName
        return if (renderedCustomProperty.expression == null) {
            buildNullableProperty(
                definition = definition,
                typeName = typeName.copy(nullable = true),
            )
        } else {
            buildProperty(
                definition = definition,
                typeName = typeName,
                initializer = CodeBlock.of("%L", renderedCustomProperty.expression),
            )
        }
    }

    private fun buildBuiltInProperty(
        definition: ConfigDefinition,
        value: ConfigValue,
    ): PropertySpec = when (value) {
        is ConfigValue.StringValue -> buildScalarProperty(
            definition = definition,
            typeName = typeNameFor(definition),
            initializer = CodeBlock.of("%S", value.value),
        )

        is ConfigValue.BooleanValue -> buildScalarProperty(
            definition = definition,
            typeName = typeNameFor(definition),
            initializer = CodeBlock.of("%L", value.value),
        )

        is ConfigValue.IntValue -> buildScalarProperty(
            definition = definition,
            typeName = typeNameFor(definition),
            initializer = CodeBlock.of("%L", value.value),
        )

        is ConfigValue.LongValue -> buildScalarProperty(
            definition = definition,
            typeName = typeNameFor(definition),
            initializer = CodeBlock.of("%LL", value.value),
        )

        is ConfigValue.DoubleValue -> buildScalarProperty(
            definition = definition,
            typeName = typeNameFor(definition),
            initializer = CodeBlock.of("%L", value.value),
        )

        is ConfigValue.StringMapValue -> buildProperty(
            definition = definition,
            typeName = typeNameFor(definition),
            initializer = renderStringMap(value.value),
        )

        is ConfigValue.StringListValue -> buildProperty(
            definition = definition,
            typeName = typeNameFor(definition),
            initializer = renderStringList(value.value),
        )

        is ConfigValue.StringListMapValue -> buildProperty(
            definition = definition,
            typeName = typeNameFor(definition),
            initializer = renderStringListMap(value.value),
        )

        is ConfigValue.EnumValue -> buildProperty(
            definition = definition,
            typeName = typeNameFor(definition),
            initializer = CodeBlock.of(
                "%L.%L",
                requireNotNull(definition.enumTypeName),
                value.value,
            ),
        )

        is ConfigValue.NullValue -> error("Null values should be handled before built-in property rendering.")
    }

    private fun buildScalarProperty(
        definition: ConfigDefinition,
        typeName: TypeName,
        initializer: CodeBlock,
    ): PropertySpec {
        val propertyBuilder = basePropertyBuilder(definition, typeName)
        if (definition.required) {
            propertyBuilder.addModifiers(KModifier.CONST)
        }
        return propertyBuilder.initializer(initializer).build()
    }

    private fun buildNullableProperty(
        definition: ConfigDefinition,
        typeName: TypeName,
    ): PropertySpec = buildProperty(
        definition = definition,
        typeName = typeName,
        initializer = CodeBlock.of("null"),
    )

    private fun buildProperty(
        definition: ConfigDefinition,
        typeName: TypeName,
        initializer: CodeBlock,
    ): PropertySpec = basePropertyBuilder(definition, typeName)
        .initializer(initializer)
        .build()

    private fun basePropertyBuilder(
        definition: ConfigDefinition,
        typeName: TypeName,
    ): PropertySpec.Builder = PropertySpec.builder(definition.propertyName, typeName)
        .addModifiers(KModifier.PUBLIC)

    private fun typeNameFor(definition: ConfigDefinition): TypeName = when (definition.kind) {
        ConfigValueKind.STRING -> String::class.asTypeName()
        ConfigValueKind.BOOLEAN -> Boolean::class.asTypeName()
        ConfigValueKind.INT -> Int::class.asTypeName()
        ConfigValueKind.LONG -> Long::class.asTypeName()
        ConfigValueKind.DOUBLE -> Double::class.asTypeName()
        ConfigValueKind.STRING_MAP -> KayanTypeNames.parameterized(
            Map::class.asClassName(),
            String::class.asTypeName(),
            String::class.asTypeName(),
        )

        ConfigValueKind.STRING_LIST -> KayanTypeNames.parameterized(
            List::class.asClassName(),
            String::class.asTypeName(),
        )

        ConfigValueKind.STRING_LIST_MAP -> KayanTypeNames.parameterized(
            Map::class.asClassName(),
            String::class.asTypeName(),
            KayanTypeNames.parameterized(
                List::class.asClassName(),
                String::class.asTypeName(),
            ),
        )

        ConfigValueKind.ENUM -> enumTypeName(definition)
    }

    private fun enumTypeName(definition: ConfigDefinition): TypeName =
        KayanTypeNames.bestGuess(requireNotNull(definition.enumTypeName))

    private fun renderStringMap(values: Map<String, String>): CodeBlock =
        values.entries
            .sortedBy { it.key }
            .toCodeBlock(prefix = "mapOf(") { builder, (key, entryValue), isFirst ->
                if (!isFirst) {
                    builder.add(", ")
                }
                builder.add("%S to %S", key, entryValue)
            }

    private fun renderStringList(values: List<String>): CodeBlock =
        values.toCodeBlock(prefix = "listOf(") { builder, value, isFirst ->
            if (!isFirst) {
                builder.add(", ")
            }
            builder.add("%S", value)
        }

    private fun renderStringListMap(values: Map<String, List<String>>): CodeBlock =
        values.entries
            .sortedBy { it.key }
            .toCodeBlock(prefix = "mapOf(") { builder, (key, entries), isFirst ->
                if (!isFirst) {
                    builder.add(", ")
                }
                builder.add("%S to %L", key, renderStringList(entries))
            }
}

private fun <T> Iterable<T>.toCodeBlock(
    prefix: String,
    renderEntry: (builder: CodeBlock.Builder, value: T, isFirst: Boolean) -> Unit,
): CodeBlock {
    val builder = CodeBlock.builder().add(prefix)
    forEachIndexed { index, value ->
        renderEntry(builder, value, index == 0)
    }
    return builder.add(")").build()
}
